[
	"System Architect",
	"Accountant",
	"Junior Technical Author",
	"Senior Javascript Developer",
	"Integration Specialist",
	"Sales Assistant",
	"Javascript Developer",
	"Software Engineer",
	"Office Manager",
	"Support Lead",
	"Regional Director",
	"Senior Marketing Designer",
	"Regional Director",
	"Chief Financial Officer (CFO)",
	"Systems Administrator",
	"Personnel Lead",
	"Development Lead",
	"Chief Marketing Officer (CMO)",
	"Pre-Sales Support",
	"Chief Executive Officer (CEO)",
	"Chief Operating Officer (COO)",
	"Regional Marketing",
	"Technical Author",
	"Post-Sales support",
	"Secretary",
	"Financial Controller",
	"Support Engineer",
	"Data Coordinator",
	"Junior Javascript Developer"
]